
export const RESET_NEW_ROUTE = 'RESET_NEW_ROUTE'
export const SET_DATA_ROUTES = 'SET_DATA_ROUTES'
export const RESET_DATA_MY_USER = 'RESET_DATA_MY_USER'
export const SET_DATA_MY_USER = 'SET_DATA_MY_USER'
export const SET_DATA_USERS = 'SET_DATA_USERS'
export const SET_DATA_NEW_ROUTE = 'SET_DATA_NEW_ROUTE'
export const SET_POSITION_SCROLL_LIST = 'SET_POSITION_SCROLL_LIST'
export const RESET_POSITION_SCROLL_LIST = 'RESET_POSITION_SCROLL_LIST'
